version: '3'

volumes:
  keycloak_postgres_test:
      driver: local

services:
  postgres:
      image: "postgres"
      volumes:
        - keycloak_postgres_test:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: keycloak++
  test-kc-keycloak:
      container_name: "test-kc-keycloak"
      hostname: "test-kc-keycloak"
      image: quay.io/keycloak/keycloak:latest
      environment:
        - "DB_VENDOR=POSTGRES"
        - "DB_ADDR=postgres"
        - "DB_DATABASE=keycloak"
        - "DB_USER=keycloak"
        - "DB_SCHEMA=public"
        - "DB_PASSWORD=keycloak++"
        - "KEYCLOAK_USER=admin"
        - "KEYCLOAK_PASSWORD=keycloak"
        - "PROXY_ADDRESS_FORWARDING=true"
        - "KEYCLOAK_FRONTEND_URL=http://test-kc-keycloak:8080/auth/"
        #- "KEYCLOAK_HOSTNAME=test-kc-keycloak"
        #- "KEYCLOAK_HTTP_PORT=8080"
        - "KEYCLOAK_LOGLEVEL=DEBUG"
      ports:
        - 8181:8080
      depends_on:
        - postgres
  test-kc-ihm:
    container_name: "test-kc-ihm"
    hostname: "test-kc-ihm"
    build:
      context: vuejs/.
      dockerfile: Dockerfile
    image: "test-kc-ihm"
    ports:
      - "8282:80"
  test-kc-secured:
    container_name: "test-kc-secured"
    hostname: "test-kc-secured"
    build:
      context: .
      dockerfile: Dockerfile
    image: "test-kc-secured"
    ports:
      - "8383:8080"
